### ISSUE TITLE
Lower quality search result pages in third-party browser engines on Android

### ISSUE THREAD

**Issue by bgrins** [mozilla/platform-tilt#12]
The web search experience is tightly integrated with a number of built-in features in Android (see https://github.com/mozilla/platform-tilt/issues/8), and the experience provided to Firefox is inferior compared to the version provided for Chrome. As seen in the screenshots below, identical search terms show less information and receive a lower quality design in Firefox on Android.

While strictly speaking this is an issue with the Google Search website, given the prominence and integration of search on Android this is a meaningful user experience gap that creates an incentive for users to not choose a third-party browser - especially those implemented with third-party browser engines, like Firefox. There are no technical limitations which would prevent this page from operating in Firefox: an equal experience should be offered.

| Chrome  | Firefox |
| ------------- | ------------- |
|<img src="https://github.com/mozilla/platform-tilt/assets/95570/eea51f92-45d3-4b48-aed1-ac8e8250fd5e" width="300" /> |<img src="https://github.com/mozilla/platform-tilt/assets/95570/43590042-bb59-43c8-97f5-42fc2610101d" width="300" /> |

**Comment by ralphm** [comment]
Interestingly, if you request the _desktop site_ version of the search results page, Firefox does show the more elaborate flight detail card.

**Comment by kbrosnan** [comment]
I created a document and screenshots of this behavior for the mobile team. I think Loren or the search Product team should have a copy. It showed many differences between the version of search Firefox gets and Chrome gets.

* Weather
* Directions
* Hotels
* Shopping
* Hex color values
* CSS color names
* Sports scores

I think there were a few other ones that came up.

**Comment by lol768** [comment]
There's some interesting discussion in Bugzilla ticket [975444](https://bugzilla.mozilla.org/show_bug.cgi?id=975444) in relation to the tier1 search experience on mobile, stretching back to 2014. Various UA overrides have been proposed and tested during that time.

**Comment by tbeest** [comment]
I don't know how is felt about the linking of add-ons here, but [this](https://addons.mozilla.org/en-US/android/addon/google-search-fixer/) one "fixes" the issue through spoofing the user agent.

**Comment by tesmite** [comment]
Until about six months ago, when using the modern search results page available in Chrome with Firefox, there was a problem with the elements not displaying properly and freezing up when an image was selected.
This has now been fixed but may have been affected by this issue.
https://github.com/wisniewskit/google-search-fixer/issues/30

**Comment by wisniewskit** [comment]
There have also been other issues with spoofing UA strings, such as Service Worker issues which caused breakage at one point (requiring disabling Service Workers at the time while spoofing), and also the fact that Google's "your devices" page would list a generic phone instead of one's actual device.

**Comment by Shirkit** [comment]
Try using Google Maps on Firefox (cached) and compared to an uncached version in Chrome while using a desktop. I have given up using Google Maps on my dektops because of that.

**Comment by rsssxd** [comment]
Enabling the option I gave you below surprisingly improves Google search in Firefox for Android. Activate it and search it on Google.

If you're still getting the old search face, reset the site data.
javascript.options.mem.gc_parallel_marking


![Screenshot_20240321-001455](https://github.com/mozilla/platform-tilt/assets/60405617/526a4a30-c0fb-4371-9374-59266ce279d2)
