### ISSUE TITLE
Add padding-bottom to container

### ISSUE THREAD

**Issue by simevidas** [mozilla/platform-tilt#17]
Without `padding-bottom`, the text at the bottom of the page is all the way at the bottom of the viewport, and it can’t be scrolled up. That’s not ideal. The user should be able to scroll that text to the middle of the screen. You could add `padding-bottom: 50svh` to `.container`.

https://github.com/mozilla/platform-tilt/assets/716405/b1c787b6-6803-4163-aa30-33be8fd9fd8e

**Comment by bgrins** [comment]
Thanks. The styles were copied over from standards-positions and could use some work - will take a look.
