### ISSUE TITLE
MacOS: inability to have Share button

### ISSUE THREAD

**Issue by paulehoffman** [mozilla/platform-tilt#21]
Firefox can't include the 
<img width="20" alt="image" src="https://github.com/mozilla/platform-tilt/assets/638939/9b71430b-f3be-4cfe-b380-9a3087842caf">
"Share" button, which limits functionality, particularly for things like sharing over Airdrop.

**Comment by mtom55** [comment]
From the [webkit blog](https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/#:~:text=Third%2Dparty%20browser%20support%20for%20Add%20to%20Home%20Screen) it states

> In iOS and iPadOS 16.4, third-party browsers can now offer their users the ability to add websites and web apps to the Home Screen from the Share menu.

and

> Applications on iOS and iPadOS present the Share menu by creating a UIActivityViewController with an array of activityItems

Presumably this means it is possible for browsers to implement the share menu, it would be nice to know the specific details about why this is not possible (AppStore rule or missing entitlement?)

Note: there should be a separate ticket(s) about being able to individually call functions/actions on the share sheet menu, without being restricted to only using the share sheet menu i.e. browsers need to be able to create their own custom menus.

**Comment by bgrins** [comment]
@paulehoffman do you know of a policy/technical limitation preventing third party apps from including this button? AFAICT this may just be a feature that isn't implemented in Firefox today (in which case I'll close the issue).

**Comment by paulehoffman** [comment]
I heard from a Mozilla person a few years ago that there was a huge technical barrier to you implementing it, but that may have changed since then. So, no, I'm not sure, but maybe ask in the part of the team that handles platform-specific stuff if the barrier is still there. If it is just a roadmap issue now, sure, close this issue.

**Comment by bgrins** [comment]
Interesting. I asked around about this and while I don't have a definitive answer, we are using [NSSharingServicePicker](https://developer.apple.com/documentation/appkit/nssharingservicepicker?language=objc) for the share UI in the touch bar, and likely could add a button in the toolbar to initiate the share UI. So based on my understanding there's not currently a technical limitation here.

**Comment by paulehoffman** [comment]
Good enough, I'll close.

**Comment by bgrins** [comment]
> Presumably this means it is possible for browsers to implement the share menu, it would be nice to know the specific details about why this is not possible (AppStore rule or missing entitlement?)

@mtom55 this issue was originally raised about macOS so it wouldn't apply to iOS or contradict anything in the linked blog post.
