### ISSUE TITLE
iOS launches Safari instead of the user's default browser

### ISSUE THREAD

**Issue by loominade** [mozilla/platform-tilt#29]
## Steps to reproduce

1. open the notes app
2. create a new note
3. write the word "test" into the note
4. select the word "test"
5. tab and hold the word
6. in the context menu tab _search web_
 
## expected behavior

the **default browser** should open the default search engine with the search term "test"

## actual behavior

**safari** opens with the default search engine with the search term "test"

## Notes

this works with every app that have the context menu enabled. I chose the notes app for easy reproducibility:

![a note with the word test and a context menu with search web selected](https://github.com/mozilla/platform-tilt/assets/11677380/88f1a81a-6a25-4f4b-b31c-ce06dd8e50b9)

**Comment by loominade** [comment]
i think this is a duplicate of #20

**Comment by Daniel15** [comment]
iOS really needs to properly support third-party browsers first (#1).

**Comment by bgrins** [comment]
Thanks for the report

> i think this is a duplicate of https://github.com/mozilla/platform-tilt/issues/20

Agreed - will close this one.

> iOS really needs to properly support third-party browsers first (https://github.com/mozilla/platform-tilt/issues/1).

They are orthogonal issues: the user's default browser choice should be respected when web pages are opened by built-in operating system features, regardless of the engine they are implemented with.
